AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  elastic-serverless-agent

  SAM Template for elastic-serverless-agent

Resources:
  ElasticServerlessAgentContinuingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: elastic-serverless-agent-continuing-dlq
      VisibilityTimeout: 900
  ElasticServerlessAgentContinuingQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: elastic-serverless-agent-continuing-queue
      RedrivePolicy: { "deadLetterTargetArn" : !GetAtt ElasticServerlessAgentContinuingDLQ.Arn, "maxReceiveCount" : 1 }
      VisibilityTimeout: 900
  ElasticServerlessAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 128
      PackageType: Zip
      CodeUri:
        Bucket: %codeURIBucket%
        Key: lambda.zip
      Runtime: python3.9
      Handler: handler.lambda_handler
      Environment:
          Variables:
              SQS_CONTINUE_URL: !Ref ElasticServerlessAgentContinuingQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ElasticServerlessAgentContinuingQueue.Arn
            BatchSize: 1
            Enabled: true
      Policies:
      - AWSLambdaExecute # Managed Policy
      - Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: 'arn:aws:s3:::*/*'
      - Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: 'arn:aws:sqs:*:*:*'
      - Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: 'arn:aws:sqs:%awsRegion%:%accountID%:elastic-serverless-agent-continuing-queue'
Metadata:
  AWS::ServerlessRepo::Application:
    Name: elastic-serverless-agent
    Description: elastic-serverless-agent
    Author: elastic
    SemanticVersion: 0.9.0

Outputs:
  ElasticServerlessAgentFunction:
    Description: "Elastic Serverless Agent"
    Value: !GetAtt ElasticServerlessAgentFunction.Arn
  ElasticServerlessAgentContinuingQueue:
    Description: "Elastic Serverless Agent"
    Value: !GetAtt ElasticServerlessAgentContinuingQueue.Arn
  ElasticServerlessAgentContinuingDLQ:
    Description: "Elastic Serverless Agent"
    Value: !GetAtt ElasticServerlessAgentContinuingDLQ.Arn
