---
## Workflow to process the JUnit test results and add a report to the checks.
name: test-reporter
on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.workflow_run.event }}
        run: echo "${{ github.event.workflow_run.pull_requests[0].number }}"
      - name: elastic/apm-pipeline-library/.github/actions/test-report
        uses: elastic/apm-pipeline-library/.github/actions/test-report@current
        with:
          artifact: test-results            # artifact name
          name: JUnit Tests                 # Name of the check run which will be created
          path: "**/*.xml"                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
          output-to: step-summary           # Write summary in the PR
      - name: 5monkeys/cobertura-action
        uses: 5monkeys/cobertura-action@v13
        with:
          skip_covered: false
          minimum_coverage: 100
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true
          pull_request_number: ${{ github.event.workflow_run.pull_requests[0].number }}
